
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const state=JSON.parse(localStorage.getItem('cpaEdgeFullState')||'{}');
function save(){localStorage.setItem('cpaEdgeFullState',JSON.stringify(state));}
function stat(k,d=0){return state[k]??d} function setstat(k,v){state[k]=v;save();}
function updateNav(){const p=location.pathname.split('/').pop()||'index.html'; $$('nav a').forEach(a=>{if(a.getAttribute('href')===p)a.classList.add('active')})}
function initLanding(){if(!$('#landingMetrics'))return; $('#totalCards').textContent=CPA.flashcards.length.toLocaleString(); $('#totalQuestions').textContent=CPA.questions.length.toLocaleString(); $('#totalLessons').textContent=CPA.lessons.length; $('#totalSims').textContent=CPA.simulations.length;}
function initCourses(){if(!$('#courseGrid'))return; $('#courseGrid').innerHTML=Object.entries(CPA.sections).map(([sec,topics])=>`<article class="card"><span class="pill">${['FAR','AUD','REG'].includes(sec)?'Core':'Discipline'}</span><h3>${sec}</h3><p class="muted">${topics.length} commercial modules · ${CPA.questions.filter(q=>q.section===sec).length} questions · ${CPA.flashcards.filter(c=>c.section===sec).length} cards</p><div class="progress-track"><div class="progress-fill" style="--value:${20+topics.length*5}%"></div></div><p>${topics.map(t=>`<span class="badge">${t}</span>`).join('')}</p></article>`).join('')}
let lessonIndex=0; function renderLessons(){if(!$('#lessonList'))return; const sec=$('#lessonFilter').value; const list=CPA.lessons.filter(l=>!sec||l.section===sec); $('#lessonList').innerHTML=list.map((l,i)=>`<button class="tab ${i===0?'active':''}" onclick="openLesson(${CPA.lessons.indexOf(l)})"><strong>${l.section}</strong> ${l.topic}<br><span class="muted">${l.minutes} min · ${l.level}</span></button>`).join(''); openLesson(CPA.lessons.indexOf(list[0]||CPA.lessons[0]));}
function openLesson(i){lessonIndex=i; const l=CPA.lessons[i]; $('#lessonTitle').textContent=l.title; $('#lessonMeta').textContent=`${l.section} · ${l.topic} · ${l.minutes} minutes`; $('#lessonBody').innerHTML=l.body.map(p=>`<p>${p}</p>`).join('')+`<div class="callout"><strong>Takeaways</strong><ul>${l.takeaways.map(t=>`<li>${t}</li>`).join('')}</ul></div><div class="callout"><strong>Exam examples</strong><ul>${l.examples.map(t=>`<li>${t}</li>`).join('')}</ul></div>`;}
function readLesson(){speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance($('#lessonTitle').innerText+'. '+$('#lessonBody').innerText); u.rate=Number($('#speed')?.value||1); speechSynthesis.speak(u)} function stopRead(){speechSynthesis.cancel()} function completeLesson(){setstat('lessonsDone',stat('lessonsDone')+1); alert('Lesson completion saved.');}
let cardDeck=[],card=0,flipped=false; function initFlash(){if(!$('#flashcard'))return; filterCards()} function filterCards(){const sec=$('#cardSec').value, diff=$('#cardDiff').value, search=$('#cardSearch').value.toLowerCase(); cardDeck=CPA.flashcards.filter(c=>(!sec||c.section===sec)&&(!diff||c.difficulty===diff)&&(!search||(c.front+c.back+c.topic).toLowerCase().includes(search))); card=0;flipped=false; $('#deckCount').textContent=cardDeck.length.toLocaleString(); renderCard()} function renderCard(){const c=cardDeck[card]||CPA.flashcards[0]; $('#cardMeta').textContent=`${c.section} · ${c.topic} · ${c.difficulty} · Card ${card+1} of ${cardDeck.length}`; $('#cardText').textContent=flipped?c.back:c.front} function flipCard(){flipped=!flipped;renderCard()} function nextCard(){card=(card+1)%Math.max(1,cardDeck.length);flipped=false;renderCard()} function knowCard(){setstat('cardsMastered',stat('cardsMastered')+1);nextCard()}
let qDeck=[],qi=0; function initQuiz(){if(!$('#quizBox'))return; filterQuiz()} function filterQuiz(){const sec=$('#quizSec').value, diff=$('#quizDiff').value; qDeck=CPA.questions.filter(q=>(!sec||q.section===sec)&&(!diff||q.difficulty===diff)); qi=0; $('#questionCount').textContent=qDeck.length.toLocaleString(); renderQ()} function renderQ(){const q=qDeck[qi]||CPA.questions[0]; $('#qMeta').textContent=`${q.section} · ${q.topic} · ${q.difficulty} · ${qi+1}/${qDeck.length}`; $('#qText').textContent=q.question; $('#qOptions').innerHTML=q.options.map((o,i)=>`<button class="option" onclick="answerQ(${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join(''); $('#qExp').textContent=q.explanation; $('#qExp').classList.remove('show')} function answerQ(i){const q=qDeck[qi]; $$('.option').forEach((b,idx)=>{b.disabled=true;if(idx===q.correct)b.classList.add('correct'); if(idx===i&&idx!==q.correct)b.classList.add('incorrect')}); setstat('attempts',stat('attempts')+1); if(i===q.correct)setstat('correct',stat('correct')+1); $('#qExp').classList.add('show')} function nextQ(){qi=(qi+1)%Math.max(1,qDeck.length);renderQ()}
function initSims(){if(!$('#simList'))return; $('#simList').innerHTML=CPA.simulations.map((s,i)=>`<button class="tab" onclick="openSim(${i})"><strong>${s.section}</strong> ${s.title}</button>`).join(''); openSim(0)} function openSim(i){const s=CPA.simulations[i]; $('#simTitle').textContent=s.title; $('#simMeta').textContent=s.section+' task-based simulation'; $('#simPrompt').textContent=s.prompt; $('#simSolution').textContent=s.solution; $('#simSolution').classList.remove('show')} function showSimSolution(){$('#simSolution').classList.add('show')} function saveSim(){localStorage.setItem('simWork',$('#simWork').value);alert('Simulation work saved locally.')}
let examIndex=0,examStarted=false,examSeconds=4*3600,examTimer; function initExam(){if(!$('#examBox'))return; renderExamQ();} function renderExamQ(){const q=CPA.exams[examIndex]; $('#examMeta').textContent=`${q.testlet} · ${q.section} · Question ${examIndex+1}/${CPA.exams.length}`; $('#examText').textContent=q.question; $('#examOptions').innerHTML=q.options.map((o,i)=>`<button class="option" onclick="examAnswer(${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join(''); $('#examExp').textContent=q.explanation; $('#examExp').classList.remove('show')} function examAnswer(i){const q=CPA.exams[examIndex]; state.examAnswers=state.examAnswers||{}; state.examAnswers[examIndex]=i; save(); $$('.option').forEach((b,idx)=>{b.disabled=true;if(idx===q.correct)b.classList.add('correct'); if(idx===i&&idx!==q.correct)b.classList.add('incorrect')}); $('#examExp').classList.add('show')} function examNext(){examIndex=Math.min(CPA.exams.length-1,examIndex+1); renderExamQ()} function examPrev(){examIndex=Math.max(0,examIndex-1); renderExamQ()} function startExam(){if(examTimer)return; examTimer=setInterval(()=>{examSeconds--; $('#timer').textContent=new Date(examSeconds*1000).toISOString().substr(11,8); if(examSeconds<=0)finishExam()},1000)} function finishExam(){clearInterval(examTimer); const ans=state.examAnswers||{}; let correct=0; CPA.exams.forEach((q,i)=>{if(ans[i]===q.correct)correct++}); $('#examReport').innerHTML=`<h3>Score Report</h3><p><strong>${Math.round(correct/CPA.exams.length*100)}%</strong> (${correct}/${CPA.exams.length})</p><p>Recommended remediation: complete FAR revenue/leases, AUD evidence, and REG basis flashcards, then retake missed questions.</p>`; $('#examReport').classList.add('show')}
function initAnalytics(){if(!$('#analytics'))return; const attempts=stat('attempts'), correct=stat('correct'); const acc=attempts?Math.round(correct/attempts*100):0; $('#analytics').innerHTML=`<article class="card metric"><p class="muted">Quiz Accuracy</p><h3>${acc}%</h3><div class="progress-track"><div class="progress-fill" style="--value:${acc}%"></div></div></article><article class="card metric"><p class="muted">Cards Mastered</p><h3>${stat('cardsMastered')}</h3></article><article class="card metric"><p class="muted">Lessons Completed</p><h3>${stat('lessonsDone')}</h3></article><article class="card metric"><p class="muted">Question Bank</p><h3>${CPA.questions.length.toLocaleString()}</h3></article>`;}
updateNav(); initLanding(); initCourses(); renderLessons(); initFlash(); initQuiz(); initSims(); initExam(); initAnalytics();
